# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SelectNulls.py
# Created on: 2013-10-10 10:09:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LANDUSE_TaxParcel__2_ = "LANDUSE.TaxParcel"
LANDUSE_SimConFirstDivision = "LANDUSE.SimConFirstDivision"
LANDUSE_SimultaneousConveyance = "LANDUSE.SimultaneousConveyance"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(LANDUSE_TaxParcel__2_, "NEW_SELECTION", "LU_CODE IS NULL")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(LANDUSE_SimConFirstDivision, "NEW_SELECTION", "(CONVEYANCE_ID IS NULL AND FIRSTDIVISIONID IS NULL) OR ( CONVEYANCE_ID IS NULL AND FIRSTDIVISIONID IS NOT NULL) OR ( CONVEYANCE_ID IS NOT NULL AND FIRSTDIVISIONID IS NULL)")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(LANDUSE_SimultaneousConveyance, "NEW_SELECTION", "CONVEYANCE_ID IS NULL")

